# fly.toml app configuration file generated for my-bbs-little-river-2037 on 2024-11-01T15:04:30-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-bbs'
primary_region = 'iad'

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1

[[services]]
internal_port = 8080
protocol = "tcp"
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0

[[services.ports]]
port = 1337
